import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { join, resolve } from "node:path";

const { execFileSyncMock, getStagedDiffMock, runOmpPrintMock } = vi.hoisted(() => ({
  execFileSyncMock: vi.fn(),
  getStagedDiffMock: vi.fn(),
  runOmpPrintMock: vi.fn(),
}));

vi.mock("./omp-print.js", () => ({
  runOmpPrint: runOmpPrintMock,
}));

vi.mock("node:child_process", () => ({
  execFileSync: execFileSyncMock,
}));

const {
  mkdtempSyncMock,
  readFileSyncMock,
  rmSyncMock,
} = vi.hoisted(() => ({
  mkdtempSyncMock: vi.fn(),
  readFileSyncMock: vi.fn(),
  rmSyncMock: vi.fn(),
}));

vi.mock("node:fs", () => ({
  mkdtempSync: mkdtempSyncMock,
  readFileSync: readFileSyncMock,
  rmSync: rmSyncMock,
}));

vi.mock("./git-operations.js", () => ({
  getStagedDiff: getStagedDiffMock,
}));

import { generateCommitMessage } from "./git-assist.js";

const originalAssistModel = process.env.BRIDGE_CODEX_ASSIST_MODEL;
const originalAssistReasoningEffort =
  process.env.BRIDGE_CODEX_ASSIST_REASONING_EFFORT;

describe("generateCommitMessage", () => {
  beforeEach(() => {
    execFileSyncMock.mockReset();
    getStagedDiffMock.mockReset();
    runOmpPrintMock.mockReset();
    mkdtempSyncMock.mockReset();
    readFileSyncMock.mockReset();
    rmSyncMock.mockReset();
    getStagedDiffMock.mockReturnValue("diff --git a/a.txt b/a.txt\n");
    mkdtempSyncMock.mockReturnValue("/tmp/codex-output-dir");
    delete process.env.BRIDGE_CODEX_ASSIST_MODEL;
    delete process.env.BRIDGE_CODEX_ASSIST_REASONING_EFFORT;
  });

  afterEach(() => {
    restoreEnvVar("BRIDGE_CODEX_ASSIST_MODEL", originalAssistModel);
    restoreEnvVar(
      "BRIDGE_CODEX_ASSIST_REASONING_EFFORT",
      originalAssistReasoningEffort,
    );
  });

  it("uses claude CLI for claude sessions", async () => {
    execFileSyncMock.mockReturnValue("feat: generated message\n");

    const message = await generateCommitMessage({
      provider: "claude",
      projectPath: "/tmp/project",
      model: "claude-sonnet-4-6",
    });

    expect(message).toBe("feat: generated message");
    expect(execFileSyncMock).toHaveBeenCalledWith(
      "claude",
      [
        "-p",
        "--model",
        "claude-sonnet-4-6",
        "Write a single Conventional Commits message in English for the staged changes below. Output only the commit message, with no quotes or explanation.",
      ],
      expect.objectContaining({
        cwd: resolve("/tmp/project"),
        input: "diff --git a/a.txt b/a.txt",
        encoding: "utf-8",
        maxBuffer: 1024 * 1024,
      }),
    );
  });

  it("uses codex CLI for codex sessions", async () => {
    readFileSyncMock.mockReturnValue("fix: generated by codex\n");

    const message = await generateCommitMessage({
      provider: "codex",
      projectPath: "/tmp/project",
      model: "gpt-5.4",
    });

    expect(message).toBe("fix: generated by codex");
    expect(execFileSyncMock).toHaveBeenCalledWith(
      "codex",
      [
        "exec",
        "-m",
        "gpt-5.6-luna",
        "-c",
        'model_reasoning_effort="none"',
        "-o",
        join("/tmp/codex-output-dir", "last-message.txt"),
        "-",
      ],
      expect.objectContaining({
        cwd: resolve("/tmp/project"),
        input:
          "Write a single Conventional Commits message in English for the staged changes below. Output only the commit message, with no quotes or explanation.\n\ndiff --git a/a.txt b/a.txt",
        encoding: "utf-8",
        maxBuffer: 1024 * 1024,
      }),
    );
    expect(readFileSyncMock).toHaveBeenCalledWith(
      "/tmp/codex-output-dir/last-message.txt",
      "utf-8",
    );
    expect(rmSyncMock).toHaveBeenCalledWith("/tmp/codex-output-dir", {
      recursive: true,
      force: true,
    });
  });

  it("ignores session codex model and uses Luna for commit assist", async () => {
    readFileSyncMock.mockReturnValue("chore: generated by codex Luna\n");

    const message = await generateCommitMessage({
      provider: "codex",
      projectPath: "/tmp/project",
      model: "gpt-5.4",
    });

    expect(message).toBe("chore: generated by codex Luna");
    expect(execFileSyncMock).toHaveBeenCalledWith(
      "codex",
      expect.arrayContaining([
        "exec",
        "-m",
        "gpt-5.6-luna",
        "-c",
        'model_reasoning_effort="none"',
      ]),
      expect.any(Object),
    );
  });

  it("uses Codex assist environment overrides", async () => {
    process.env.BRIDGE_CODEX_ASSIST_MODEL = "gpt-oss:20b-cloud";
    process.env.BRIDGE_CODEX_ASSIST_REASONING_EFFORT = "low";
    readFileSyncMock.mockReturnValue("fix: custom gateway\n");

    await generateCommitMessage({
      provider: "codex",
      projectPath: "/tmp/project",
      model: "ignored-session-model",
    });

    expect(execFileSyncMock).toHaveBeenCalledWith(
      "codex",
      expect.arrayContaining([
        "exec",
        "-m",
        "gpt-oss:20b-cloud",
        "-c",
        'model_reasoning_effort="low"',
      ]),
      expect.any(Object),
    );
  });

  it("uses omp -p with the diff on stdin for omp sessions", async () => {
    runOmpPrintMock.mockResolvedValue("feat(app): add omp\n\nbody\n");

    const message = await generateCommitMessage({
      provider: "omp",
      projectPath: "/tmp/project",
      model: "baseten/zai-org/GLM-5.3-Fast",
    });

    expect(message).toBe("feat(app): add omp");
    expect(runOmpPrintMock).toHaveBeenCalledWith({
      cwd: resolve("/tmp/project"),
      prompt:
        "Write a single Conventional Commits message in English for the staged changes below. Output only the commit message, with no quotes or explanation.",
      stdin: "diff --git a/a.txt b/a.txt",
      model: "baseten/zai-org/GLM-5.3-Fast",
    });
    expect(execFileSyncMock).not.toHaveBeenCalled();
  });

  it("rejects when omp -p fails", async () => {
    runOmpPrintMock.mockRejectedValue(new Error("omp exited with code 1"));

    await expect(
      generateCommitMessage({ provider: "omp", projectPath: "/tmp/project" }),
    ).rejects.toThrow(/omp exited/);
  });

  it("fails when no files are staged", async () => {
    getStagedDiffMock.mockReturnValue("");

    await expect(
      generateCommitMessage({
        provider: "claude",
        projectPath: "/tmp/project",
      }),
    ).rejects.toThrow(/Nothing to commit/);
  });

  it("fails when CLI returns empty output", async () => {
    execFileSyncMock.mockReturnValue(" \n");

    await expect(
      generateCommitMessage({
        provider: "claude",
        projectPath: "/tmp/project",
      }),
    ).rejects.toThrow(/empty output/);
  });
});

function restoreEnvVar(key: string, value: string | undefined): void {
  if (value === undefined) {
    delete process.env[key];
    return;
  }
  process.env[key] = value;
}
